config/routes.rb
Rails.application.routes.draw do
  root to: 'cars#index'

  resources :cars do
    resources :services
  end
  
  resources :vendors
  resources :parts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :services
  belongs_to :user
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :vendor
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :cars
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :parts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  before_action :find_car, only: [:show, :edit, :update, :destroy]

  def index
    @car = Car.all.order('created_at DESC')
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :year, :vin, :mileage, :transmission, :drive_type, :color)
  end

  def find_car
    @car = Car.find_by(params[:id])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :require_login
  before_action :find_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = current_user.cars.order('created_at DESC')
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = current_user.cars.new(car_params)

    if @car.save
      redirect_to @car
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :year, :vin, :mileage, :transmission, :drive_type, :color)
  end

  def find_car
    @car = Car.find(params[:id])
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :require_login
  before_action :find_part, only: [:show, :edit, :update, :destroy]

  def index
    @parts = Parts.all.order('created_at DESC')
  end

  def show
  end

  def new
    @part = Part.new
  end

  def create
    @part = Part.create(part_params)

    if @part.save
      redirect_to @part
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @part.update(part_params)
      redirect_to @part
    else
      render :edit
    end
  end

  def destroy
    @part.destroy
    redirect_to parts_path
  end

  private

  def part_params
    params.require(:part).permit(:part_number, :part_name, :cost, :part_designation, :quantity)
  end

  def find_part
    @part =  Part.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :require_login
  before_action :find_service, only: [:edit, :update, :destroy]

  def new
    @car = Car.find(params[:car_id])
    # @parts = Part.all
    # @vendors = Vendor.all
    @service = @car.services.build
  end

  def create
    @car = Car.find(params[:car_id])
    # @parts = Part.all
    # @vendors = Vendor.all
    @service = @car.services.build(service_params)
    # @service.user = current_user

    if @service.save
      redirect_to @car
    else
      render :new
    end
  end

  def edit
    @car = @service.car
  end

  def update
    @car = @service.car

    if @service.update(service_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    car = @service.car

    @service.destroy
    redirect_to car
  end

  private

  def service_params
    params.require(:service).permit(:service_date, :service_mileage, :work_description, :work_hours)
  end

  def find_service
    @service = Service.find(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :require_login
  before_action :find_vendor, only: [:show, :edit, :update, :destroy]

  def index
    @vendors = Vendors.all.order('created_at DESC')
  end

  def show
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.create(vendor_params)

    if @vendor.save
      redirect_to @vendor
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @vendor.update(vendor_params)
      redirect_to @vendor
    else
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    redirect_to vendors_path
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name, :contact, :website, :location)
  end

  def find_vendor
    @vendor = Vendor.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/cars/edit.html.erb
<article id="car">
  <div class="formContainer">
    <h1>Edit your car</h1>

    <%= form_for @car do |form| %>
      <p> Brand: <%= form.text_field :brand, class: "textfields" %></p>
      <p> Model: <%= form.text_field :model, class: "textfields" %></p>
      <p> Year: <%= form.text_field :year, class: "textfields" %></p>
      <p> Vin: <%= form.text_field :vin, class: "textfields" %></p>
      <p> Mileage: <%= form.text_field :mileage, class: "textfields" %></p>
      <p> Transmission: <%= form.text_field :transmission, class: "textfields" %></p>
      <p> Drive Type: <%= form.text_field :drive_type, class: "textfields" %></p>
      <p> Color: <%= form.text_field :color, class: "textfields" %></p>
      <%# <p> <%= form.hidden_field :user_id, :value => current_user.id  </p> %>
      <ul class="actions">
        <%= form.submit "Edit Car", class: "inputs" %>
      </ul>
    <% end %>

    <%= link_to 'Back to Cars', cars_path %>

  </div>
</article>

app/views/cars/index.html.erb
<article>
  <div>
    <ol>
      <h1> Your Cars </h1>
      <br />

      <% @cars.each do |car| %>
        <h3 id="test1">
          <li><%= link_to "#{car.brand} - #{car.model}", car_path(car) %></li>
        </h3>
      <% end %>
    </ol>

    <%= link_to 'Add a car', new_car_path %>
  </div>
</article>

app/views/cars/new.html.erb
<article id="contact">
  <div class="formContainer">
    <h1>Cars</h1>

    <%= form_for @car do |form| %>
      <p> Brand: <%= form.text_field :brand, class: "textfields" %></p>
      <p> Model: <%= form.text_field :model, class: "textfields" %></p>
      <p> Year: <%= form.text_field :year, class: "textfields" %></p>
      <p> Vin: <%= form.text_field :vin, class: "textfields" %></p>
      <p> Mileage: <%= form.text_field :mileage, class: "textfields" %></p>
      <p> Transmission: <%= form.text_field :transmission, class: "textfields" %></p>
      <p> Drive Type: <%= form.text_field :drive_type, class: "textfields" %></p>
      <p> Color: <%= form.text_field :color, class: "textfields" %></p>
      <%# <p> <%= form.hidden_field :user_id, :value => current_user.id  </p> %>
      <ul class="actions">
        <%= form.submit "Create Car", class: "inputs" %>
      </ul>
    <% end %>

    <%= link_to 'Back to Cars', cars_path %>

  </div>
</article>

app/views/cars/show.html.erb
<%= link_to 'Show All My Cars', cars_path(@cars) %>
<%= link_to 'Edit Car', edit_car_path(@car) %>
<%= link_to 'Delete Car', car_path(@car), class: 'card-footer-item has-text-weight-bold',
  method: :delete, data: { confirm: 'Are you sure you want to delete this car?' } %>

<article id="contact">
  <div class="formContainer">
    <h2><%= @car.brand %> - <%= @car.model %> Information </h2>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Brand</th>
          <th scope="col">Model</th>
          <th scope="col">Year</th>
          <th scope="col">Vin Number</th>
          <th scope="col">Mileage</th>
          <th scope="col">Transmission</th>
          <th scope="col">Drive Type</th>
          <th scope="col">Color</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @car.brand %></td>
          <td><%= @car.model %></td>
          <td><%= @car.year %></td>
          <td><%= @car.vin %></td>
          <td><%= @car.mileage %></td>
          <td><%= @car.transmission %></td>
          <td><%= @car.drive_type %></td>
          <td><%= @car.color %></td>
        </tr>
      </tbody>
    </table>
    <br />
  </div>
</article>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">Services:</h3>
<%= link_to 'Add new Service', new_car_service_path(@car) %>
    <h4 class="card-subtitle mb-2 text-muted">
      <ol>
        <% counter = 0 %>
        <% @car.services.each do |service| %>
          <% if service %>
            <% partial = service %>
            <% counter += 1 %>
          <% else %>
            <%= partial = " " %>
          <% end %>
          <%= render partial: partial, object: service, locals: { counter: counter } %>
        <% end %>
        <% if counter == 0 %>
          <h2><strong><%= "You don't have any service for your car!" %></strong></h2>
        <% end %>
      </ol>
    </h4>
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/parts/create.html.erb
<h1>Parts#create</h1>
<p>Find me in app/views/parts/create.html.erb</p>

app/views/parts/destroy.html.erb
<h1>Parts#destroy</h1>
<p>Find me in app/views/parts/destroy.html.erb</p>

app/views/parts/edit.html.erb
<h1>Parts#edit</h1>
<p>Find me in app/views/parts/edit.html.erb</p>

app/views/parts/index.html.erb
<h1>Parts#index</h1>
<p>Find me in app/views/parts/index.html.erb</p>

app/views/parts/new.html.erb
<h1>Parts#new</h1>
<p>Find me in app/views/parts/new.html.erb</p>

app/views/parts/show.html.erb
<h1>Parts#show</h1>
<p>Find me in app/views/parts/show.html.erb</p>

app/views/parts/update.html.erb
<h1>Parts#update</h1>
<p>Find me in app/views/parts/update.html.erb</p>

app/views/services/_service.html.erb
<%= link_to 'Edit Service', edit_car_service_path(service.car, service) %>
<%= link_to 'Delete Service', car_service_path(service.car, service), class: 'card-footer-item has-text-weight-bold',
  method: :delete, data: { confirm: 'Are you sure you want to delete this car?' } %>

<article id="contact">
  <div class="formContainer">
    <h2><%= @car.brand %> - <%= @car.model %> Service <%= counter %></h2>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Mileage</th>
          <th scope="col">Description</th>
          <th scope="col">Hours</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= service.service_date %></td>
          <td><%= service.service_mileage %></td>
          <td><%= service.work_description %></td>
          <td><%= service.work_hours %></td>
        </tr>
      </tbody>
    </table>
    <br />
  </div>
</article>

app/views/services/edit.html.erb
<article id="service">
  <div class="formContainer">
    <h1>Edit your car service</h1>

    <%= form_with model: [@car, @service] do |form| %>
      <p> Service date: <%= form.text_field :service_date, class: "textfields" %></p>
      <p> Service mileage: <%= form.text_field :service_mileage, class: "textfields" %></p>
      <p> Work description: <%= form.text_area :work_description, class: "textfields" %></p>
      <p> Work hours: <%= form.text_field :work_hours, class: "textfields" %></p>
      <ul class="actions">
        <%= form.submit "Edit Service", class: "inputs" %>
      </ul>
    <% end %>

    <%= link_to 'Back to Services', root_path %>

  </div>
</article>

app/views/services/new.html.erb
<article id="service">
  <div class="formContainer">
    <h1>Your car service</h1>

    <%= form_with model: [@car, @service] do |form| %>
      <p> Service date: <%= form.text_field :service_date, class: "textfields" %></p>
      <p> Service mileage: <%= form.text_field :service_mileage, class: "textfields" %></p>
      <p> Work description: <%= form.text_area :work_description, class: "textfields" %></p>
      <p> Work hours: <%= form.text_field :work_hours, class: "textfields" %></p>
      <ul class="actions">
        <%= form.submit "Add Service", class: "inputs" %>
      </ul>
    <% end %>

    <%= link_to 'Back to My Cars', cars_path %>

  </div>
</article>

app/views/services/show.html.erb
<%= link_to 'Show All My Cars', cars_path(@cars) %>
<%= link_to 'New Service', new_car_service_path(@car) %>
<%= link_to 'Edit Car', edit_car_path(@car) %>
<%= link_to 'Delete Car', car_path(@car), class: 'card-footer-item has-text-weight-bold',
  method: :delete, data: { confirm: 'Are you sure you want to delete this car?' } %>

<article id="contact">
  <div class="formContainer">
    <h2><%= @car.brand %> - <%= @car.model %> Information </h2>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Brand</th>
          <th scope="col">Model</th>
          <th scope="col">Year</th>
          <th scope="col">Vin Number</th>
          <th scope="col">Mileage</th>
          <th scope="col">Transmission</th>
          <th scope="col">Drive Type</th>
          <th scope="col">Color</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @car.brand %></td>
          <td><%= @car.model %></td>
          <td><%= @car.year %></td>
          <td><%= @car.vin %></td>
          <td><%= @car.mileage %></td>
          <td><%= @car.transmission %></td>
          <td><%= @car.drive_type %></td>
          <td><%= @car.color %></td>
        </tr>
      </tbody>
    </table>
    <br />
  </div>
</article>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">Services:</h3>
    <h4 class="card-subtitle mb-2 text-muted">
      <ol>
        <%= render @car.services %>
      </ol>
    </h4>
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
    <% if signed_in? %>
      <ul class="nav navbar-nav">
      <li><%= link_to 'Add Car', new_car_path %></li>
      </ul>
    <% end %>

    <ul class="nav navbar-nav pull-right">
      <% if signed_in? %>
      <li><span><%= current_user.email %></span></li>
      <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
      <% else %>
      <li><%= link_to 'Sign in', sign_in_path %></li>
    <% end %>
  </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/vendors/create.html.erb
<h1>Vendors#create</h1>
<p>Find me in app/views/vendors/create.html.erb</p>

app/views/vendors/destroy.html.erb
<h1>Vendors#destroy</h1>
<p>Find me in app/views/vendors/destroy.html.erb</p>

app/views/vendors/edit.html.erb
<h1>Vendors#edit</h1>
<p>Find me in app/views/vendors/edit.html.erb</p>

app/views/vendors/index.html.erb
<h1>Vendors#index</h1>
<p>Find me in app/views/vendors/index.html.erb</p>

app/views/vendors/new.html.erb
<h1>Vendors#new</h1>
<p>Find me in app/views/vendors/new.html.erb</p>

app/views/vendors/show.html.erb
<h1>Vendors#show</h1>
<p>Find me in app/views/vendors/show.html.erb</p>

app/views/vendors/update.html.erb
<h1>Vendors#update</h1>
<p>Find me in app/views/vendors/update.html.erb</p>